language: node_js
sudo: required
before_install:
- if [[ ! -z "$GCLOUD_CREDENTIALS" ]]; then echo $GCLOUD_CREDENTIALS | openssl enc -d -aes-256-cbc -base64 -A -k $GCLOUD_CREDENTIALS_KEY > fhir-org-cds-services.json; fi
branches:
  only:
    - master
node_js:
  - 'lts/*'
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:report
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: fhir-org-cds-services.json
  project: fhir-org-cds-services
  default: true
  no_promote: true
  no_stop_previous_version: true
